export const products = [
  {
    id: 1,
    name: "Organic Cotton Sweater",
    price: 89.99,
    description:
      "Perfect for those brutal Chicago winters by the lake. This sweater will keep you toasty from the Mag Mile to Wicker Park, no dibs required.",
    image: "/images/md-salman-tWOz2_EK5EQ-unsplash.jpg",
    categories: ["Sweaters", "Organic", "New Arrival"],
    colors: ["Sage", "Terracotta", "Natural"],
    rating: 4.8,
    reviewCount: 24,
  },
  {
    id: 2,
    name: "Recycled Wool Cardigan",
    price: 119.99,
    description:
      "Warm enough for a Bears game at Soldier Field in December. This cardigan laughs in the face of lake effect snow while keeping your carbon footprint smaller than a Chicago-style hot dog.",
    image: "/images/md-salman-tWOz2_EK5EQ-unsplash.jpg",
    categories: ["Cardigans", "Recycled", "Bestseller"],
    colors: ["Charcoal", "Navy", "Burgundy"],
    rating: 4.9,
    reviewCount: 42,
  },
  {
    id: 3,
    name: "Hemp Linen Shirt",
    price: 69.99,
    description:
      "Breathable enough for those two weeks of Chicago summer when it's hotter than the frunchroom at your aunt's Bridgeport bungalow. Perfect for a stroll along the 606.",
    image: "/images/md-salman-tWOz2_EK5EQ-unsplash.jpg",
    categories: ["Shirts", "Hemp", "Summer"],
    colors: ["White", "Sand", "Olive"],
    rating: 4.7,
    reviewCount: 18,
  },
  {
    id: 4,
    name: "Fair Trade Denim Jeans",
    price: 99.99,
    description:
      "Tough enough for a bike ride along the Lakefront Trail and stylish enough for dinner in the West Loop. These jeans will last longer than your wait for the Red Line during rush hour.",
    image: "/images/md-salman-tWOz2_EK5EQ-unsplash.jpg",
    categories: ["Jeans", "Fair Trade", "Essentials"],
    colors: ["Indigo", "Black", "Light Wash"],
    rating: 4.6,
    reviewCount: 37,
  },
  {
    id: 5,
    name: "Bamboo Lounge Set",
    price: 129.99,
    description:
      "So comfortable you'll want to wear it while ordering Lou Malnati's and watching da Bulls. Perfect for those days when you're avoiding the Hawk (that wind, oof) and staying inside.",
    image: "/images/md-salman-tWOz2_EK5EQ-unsplash.jpg",
    categories: ["Loungewear", "Bamboo", "Comfort"],
    colors: ["Gray", "Dusty Rose", "Sage"],
    rating: 5.0,
    reviewCount: 29,
  },
  {
    id: 6,
    name: "Upcycled Patchwork Jacket",
    price: 149.99,
    description:
      "As unique as Cloud Gate (don't call it The Bean). This one-of-a-kind jacket will turn heads from Logan Square to Hyde Park and everywhere in between.",
    image: "/images/md-salman-tWOz2_EK5EQ-unsplash.jpg",
    categories: ["Jackets", "Upcycled", "Limited Edition"],
    colors: ["Multi"],
    rating: 4.9,
    reviewCount: 15,
  },
  {
    id: 7,
    name: "Tencel Maxi Dress",
    price: 119.99,
    description:
      "Elegant enough for a night at the Chicago Theatre and comfortable enough for an architecture boat tour. Flows like the Chicago River on St. Patrick's Day (but much more eco-friendly).",
    image: "/images/md-salman-tWOz2_EK5EQ-unsplash.jpg",
    categories: ["Dresses", "Tencel", "Occasion"],
    colors: ["Forest Green", "Midnight Blue", "Rust"],
    rating: 4.8,
    reviewCount: 31,
  },
  {
    id: 8,
    name: "Recycled Polyester Raincoat",
    price: 159.99,
    description:
      "Because in Chicago, it can be sunny, raining, and snowing all in one day. This raincoat will keep you dry from the Hancock to the Willis Tower (we still call it Sears).",
    image: "/images/md-salman-tWOz2_EK5EQ-unsplash.jpg",
    categories: ["Outerwear", "Recycled", "Weather-Resistant"],
    colors: ["Yellow", "Navy", "Clear"],
    rating: 4.7,
    reviewCount: 22,
  },
  {
    id: 9,
    name: "Organic Cotton Yoga Set",
    price: 89.99,
    description:
      "Perfect for yoga in Millennium Park or a quick jog along the 18-mile Lakefront Trail. More comfortable than sitting in Cubs traffic on Addison and more flexible than trying to find parking in Lakeview.",
    image: "/images/md-salman-tWOz2_EK5EQ-unsplash.jpg",
    categories: ["Activewear", "Organic", "Wellness"],
    colors: ["Lavender", "Earth", "Black"],
    rating: 4.9,
    reviewCount: 47,
  },
];
